directories:
  base: ""
  subdirs:
    output: "renders"
camera:
  resolution: (1920, 1080)
  background_color: "#020204"
  fps: 30
file_writer:
  ffmpeg_bin: "/home/alex/work/tachyon_wt1/video/bin/ffmpeg"
text:
  font: "New Computer Modern"
  alignment: "LEFT"
